import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import "./globals.scss";
import "./index.styles.scss";
import "./components.scss";
import AppWrapper from "@/components/App";
import { DataComponent } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AppWrapper>
            <DataComponent>

            {children}
            </DataComponent>
          </AppWrapper>
        </StoreProvider>
        </body>
    </html>
  );
}
